ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=flaskr
      export FLASK_ENV=development
    init: |
      pip install -e .
      flask init-db
      dd if=/dev/zero of=upload_test bs=1M count=10000
      gp stop
    command: |
      flask run

vscode:
  extensions:
    - ms-python.python
